source_url: https://xkcd.com/
db_file: database.json
db_path: pkg/database/
index_file: indexer.json
parallel: 10 #  эмпирически выявил, что такое отношение скачает весь пул задач быстрее без потребления лишних ресурсов
srv_port: 8791
pg_dsn: user=postgres password=password host=localhost port=5436 dbname=yadro sslmode=disable pool_max_conns=10