source_url: https://xkcd.com/
db_file: silly.json
db_path: pkg/database/
until: 24
parallel: 50 #  эмпирически выявил, что такое отношение скачает весь пул задач быстрее без потреблениял ишних ресурсов 